// examples/react-example.tsx
import React from 'react';
import { 
  createLogger, 
  ConsoleTransport, 
  LokiTransport, 
  DatadogTransport,
  SentryTransport,
  HermesErrorBoundary,
  withHermesLogging,
  useReactHermesLogger,
  LogLevel
} from 'hermes-trace';

const logger = createLogger({
  level: LogLevel.DEBUG,
  transports: [
    new ConsoleTransport({ level: LogLevel.DEBUG }),
    new LokiTransport({
      url: 'http://localhost:3100',
      labels: { service: 'my-react-app' }
    }),
    new DatadogTransport({
      apiKey: 'your-datadog-api-key',
      service: 'my-react-app',
      env: 'production'
    }),
    new SentryTransport({
      dsn: 'your-sentry-dsn',
      environment: 'production'
    })
  ],
  context: { userId: '12345' }
});

const ErrorFallback: React.FC<{ error?: Error; resetError: () => void }> = ({ error, resetError }) => (
  <div role="alert" style={{ padding: '20px', border: '1px solid red' }}>
    <h2>Something went wrong:</h2>
    <pre>{error?.message}</pre>
    <button onClick={resetError}>Try again</button>
  </div>
);

const MyComponent: React.FC = () => {
  const { logInfo, logError, logWarn } = useReactHermesLogger(logger, 'MyComponent');

  const handleClick = () => {
    logInfo('Button clicked', { action: 'click', timestamp: Date.now() });
  };

  const handleError = () => {
    try {
      throw new Error('Intentional error for testing');
    } catch (error) {
      logError('Error in button handler', error as Error, { action: 'error-test' });
    }
  };

  React.useEffect(() => {
    logInfo('Component mounted');
    return () => logInfo('Component will unmount');
  }, [logInfo]);

  return (
    <div>
      <h3>My Component</h3>
      <button onClick={handleClick}>Log Info</button>
      <button onClick={handleError}>Trigger Error</button>
    </div>
  );
};

const EnhancedComponent = withHermesLogging(MyComponent, logger, 'EnhancedMyComponent');

const App: React.FC = () => {
  React.useEffect(() => {
    logger.info('React app started', { framework: 'React', version: '18.x' });
  }, []);

  return (
    <HermesErrorBoundary 
      logger={logger}
      fallback={ErrorFallback}
      tags={['app-boundary']}
      context={{ app: 'react-example' }}
    >
      <div className="App">
        <header>
          <h1>HermesTrace React Example</h1>
        </header>
        <main>
          <MyComponent />
          <EnhancedComponent />
        </main>
      </div>
    </HermesErrorBoundary>
  );
};

export default App;

// examples/vue-example.vue
<template>
  <div class="vue-example">
    <header>
      <h1>HermesTrace Vue Example</h1>
    </header>
    <main>
      <div>
        <h3>Vue Component</h3>
        <button @click="handleClick">Log Info</button>
        <button @click="handleError">Trigger Error</button>
        <button @click="handleWarning">Log Warning</button>
      </div>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { 
  createLogger, 
  ConsoleTransport, 
  LokiTransport, 
  DatadogTransport,
  LogLevel,
  createVuePlugin 
} from 'hermes-trace';

const logger = createLogger({
  level: LogLevel.DEBUG,
  transports: [
    new ConsoleTransport({ level: LogLevel.DEBUG }),
    new LokiTransport({
      url: 'http://localhost:3100',
      labels: { service: 'my-vue-app' }
    }),
    new DatadogTransport({
      apiKey: 'your-datadog-api-key',
      service: 'my-vue-app',
      env: 'production'
    })
  ],
  context: { userId: '12345' }
});

// Install the Vue plugin globally
// app.use(createVuePlugin(logger));

export default defineComponent({
  name: 'VueExample',
  created() {
    this.$hermesLogger.info('Vue component created', { 
      component: 'VueExample',
      framework: 'Vue',
      version: '3.x' 
    });
  },
  methods: {
    handleClick() {
      this.$logInfo('Button clicked', { 
        action: 'click', 
        timestamp: Date.now() 
      });
    },
    
    handleError() {
      try {
        throw new Error('Intentional error for testing');
      } catch (error) {
        this.$logError('Error in button handler', error, { 
          action: 'error-test' 
        });
      }
    },
    
    handleWarning() {
      this.$logWarn('This is a warning message', { 
        action: 'warning-test',
        level: 'warn' 
      });
    }
  }
});
</script>

<style scoped>
.vue-example {
  font-family: Arial, sans-serif;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

button {
  margin: 5px;
  padding: 10px 15px;
  background: #42b883;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background: #369870;
}
</style>
